name: Maven Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # можно заменить на 'adopt' или 'zulu' в зависимости от предпочтений
          server-id: mvn-repo
          settings-path: ${{ github.workspace }}

      - name: Set up
        run: |
 
          
          git config --global user.email "androkc1999@example.com"
          git config --global user.name "androkc"

          mvn release:prepare --batch-mode -Dgit.token=${{ env.PAT_TOKEN }}
          
          cat > $GITHUB_WORKSPACE/settings.xml <<EOL
          <settings>
           <servers>
            <server>
              <id>nexus</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
             </server>
            </servers>
          </settings>
          EOL
          
          mvn release:perform -s $GITHUB_WORKSPACE/settings.xml
        shell: /usr/bin/bash -e {0}
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}









