name: Maven Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build and Deploy
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: mvn clean release:prepare release:perform deploy




