name: Maven Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "androkc1999@gmail.com"
          git config --global user.name "androkc"  

      - name: Set PAT_TOKEN
        run: echo "PAT_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build and Deploy
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run:
          mvn clean release:prepare -Dgit.token=${{ secrets.GITHUB_TOKEN }} -X -e





